# Generated by Django 4.0.3 on 2022-03-13 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('awwardapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='profile_image',
            new_name='profile',
        ),
    ]
